version: "2"
services:
  web:
    container_name: event-manager
    restart: always
    build: ./client
    ports:
      - 2222:80
  mongo:
     container_name: mongo
     restart: always
     image: mongo
     volumes:
       - ./volumes/data:/data/db
     ports:
       - 27017:27017
  api:
     container_name: event-manager-api
     restart: always
     build: ./api
     ports:
       - 3000:3000
     links:
       - mongo
  updater:
     container_name: student-updater
     restart: always
     build: ./student-updater
     links:
       - mongo
